#!/usr/bin/env bash

# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its
# affiliates. All rights reserved.
#
# This code is DA Background Intellectual Property as defined in the
# Master Product Agreement between DA and the client.

set -eou pipefail

source "scripts/libcli.source"

PYTHONPATH=$(pwd)/target/_gen .venv/bin/python3 -m python "$@"
